name: Deploy Application Devops

on:
  push:
      branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Build project
      run: mvn clean install
    - name: Login Docker Hub
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{DOCKER_PASSWORD}}
    - name: Build docker image
      run: docker build -t gabrielmerds/todolist-challenge .
    - name: Push docker image
      run: docker push gabrielmerds/todolist-challenge




      
