name: Deploy Application Devops

on:
  push:
      branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Build project
      run: mvn clean install
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build docker image
      run: docker build -t gabrielmerds/todolist-challenge .
    - name: Push image docker
      run: docker push gabrielmerds/todolist-challenge




      
